//! Differential verification for ability interactions.
//!
//! The corpus is generated by `tests/generate_ability_interactions.mjs` from the
//! pinned Showdown checkout and records the reference state at every decision
//! boundary (RNG seed, HP, status, boosts, types, items, volatiles, side and
//! field effects, request legality).
//!
//! Fixtures whose featured ability is not yet ported are smoke-checked with the
//! feature swapped for a neutral ported ability: the rest of the battle must be
//! inside the native subset today. The moment `Ability::is_ported()` flips, the
//! same fixture becomes a full boundary comparison with no regeneration needed.
use pa3_engine::{
    actions::{ActionKind, AtomicAction, RequestKind},
    assets::Dex,
    state::{BattleState, SideId, Team},
};
use serde::Deserialize;
use sha2::Digest;
use std::path::Path;

#[derive(Deserialize)]
struct Corpus {
    oracle_commit: String,
    format: String,
    generator_sha256: String,
    fixtures: Vec<Fixture>,
}

#[derive(Deserialize)]
struct Fixture {
    name: String,
    seed: [u16; 4],
    ability: String,
    teams: [Team; 2],
    initial: Expected,
    steps: Vec<Step>,
    #[allow(dead_code)]
    coverage: Option<serde_json::Value>,
}

#[derive(Deserialize)]
struct Step {
    side: SideId,
    actions: Vec<AtomicAction>,
    command: String,
    expected: Expected,
}

#[derive(Deserialize)]
struct Expected {
    turn: u16,
    rng_seed: String,
    ended: bool,
    winner: Option<String>,
    field: Vec<(u16, u16, usize)>,
    sides: Vec<ExpectedSide>,
}

#[derive(Deserialize)]
struct ExpectedSide {
    request: RequestKind,
    conditions: Vec<(u16, u16)>,
    pokemon: Vec<ExpectedMon>,
}

#[derive(Deserialize)]
struct ExpectedMon {
    roster: u8,
    species: u16,
    hp: u16,
    max_hp: u16,
    fainted: bool,
    active_slot: Option<u8>,
    status: u16,
    boosts: [i8; 7],
    stats: [u16; 6],
    ability: u16,
    ability_ending: bool,
    item: u16,
    previous_item: u16,
    types: Vec<u16>,
    pp: Vec<u8>,
    disabled: Vec<bool>,
    volatiles: Vec<u16>,
}

fn world(state: &BattleState) -> serde_json::Value {
    let envelope: serde_json::Value = serde_json::from_slice(&state.snapshot().unwrap()).unwrap();
    serde_json::from_str(envelope["payload"].as_str().unwrap()).unwrap()
}

fn check(state: &BattleState, expected: &Expected, context: &str) {
    let world = world(state);
    assert_eq!(world["turn"].as_u64().unwrap() as u16, expected.turn, "{context} turn");
    assert_eq!(
        state.rng_seed().iter().map(|x| x.to_string()).collect::<Vec<_>>().join(","),
        expected.rng_seed,
        "{context} RNG"
    );
    let mut actual_field: Vec<(u16, u16, usize)> = world["field"]
        .as_object()
        .unwrap()
        .iter()
        .map(|(id, effect)| {
            let owner = if effect["source"][0] == "P1" { 0 } else { 1 };
            (id.parse().unwrap(), effect["duration"].as_u64().unwrap() as u16, owner)
        })
        .collect();
    actual_field.sort_by_key(|effect| effect.0);
    assert_eq!(actual_field, expected.field, "{context} battle field");
    for (index, expected_side) in expected.sides.iter().enumerate() {
        let side = if index == 0 { SideId::P1 } else { SideId::P2 };
        let view = state.observe(side);
        assert_eq!(view.outcome.terminated, expected.ended, "{context} terminated");
        if expected.ended {
            assert_eq!(
                view.outcome.winner.map(|w| if w == SideId::P1 { "p1" } else { "p2" }),
                expected.winner.as_deref(),
                "{context} winner"
            );
        }
        assert_eq!(view.request.kind, expected_side.request, "{context} request kind");
        let actual_conditions: Vec<(u16, u16)> = world["sides"][index]["conditions"]
            .as_object()
            .unwrap()
            .iter()
            .map(|(id, state)| (id.parse().unwrap(), state["duration"].as_u64().unwrap() as u16))
            .collect::<std::collections::BTreeMap<_, _>>()
            .into_iter()
            .collect();
        assert_eq!(actual_conditions, expected_side.conditions, "{context} side {index} conditions");
        for expected_mon in &expected_side.pokemon {
            let mon = &world["sides"][index]["pokemon"][expected_mon.roster as usize];
            let own = &view.own.pokemon[expected_mon.roster as usize];
            let label = format!("{context} side {index} mon {}", expected_mon.roster);
            assert_eq!(mon["hp"].as_u64().unwrap() as u16, expected_mon.hp, "{label} hp");
            assert_eq!(own.stats[0], expected_mon.max_hp, "{label} max hp");
            assert_eq!(mon["fainted"].as_bool().unwrap(), expected_mon.fainted, "{label} fainted");
            assert_eq!(
                mon["active_slot"].as_u64().map(|x| x as u8),
                expected_mon.active_slot,
                "{label} active slot"
            );
            assert_eq!(own.status, expected_mon.status, "{label} status");
            assert_eq!(own.boosts, expected_mon.boosts, "{label} boosts");
            assert_eq!(own.stats, expected_mon.stats, "{label} stats");
            assert_eq!(own.ability, expected_mon.ability, "{label} ability");
            assert_eq!(
                mon["ability_ending"].as_bool().unwrap_or(false),
                expected_mon.ability_ending,
                "{label} ability ending"
            );
            assert_eq!(own.item, expected_mon.item, "{label} item");
            assert_eq!(own.previous_item, expected_mon.previous_item, "{label} previous item");
            assert_eq!(own.types, expected_mon.types, "{label} types");
            assert_eq!(
                own.moves.iter().map(|m| m.pp).collect::<Vec<_>>(),
                expected_mon.pp,
                "{label} pp"
            );
            assert_eq!(
                own.moves.iter().map(|m| m.disabled).collect::<Vec<_>>(),
                expected_mon.disabled,
                "{label} disabled flags"
            );
            let mut volatiles: Vec<u16> = mon["volatiles"]
                .as_object()
                .unwrap()
                .keys()
                .map(|id| id.parse().unwrap())
                .collect();
            volatiles.sort_unstable();
            assert_eq!(volatiles, expected_mon.volatiles, "{label} volatiles");
            assert_eq!(own.species, expected_mon.species, "{label} species");
        }
    }
}

#[test]
fn ability_interactions_match_reference_when_ported() {
    // Ported abilities whose interaction fixture currently diverges from the
    // pinned reference. Each entry must still fail: a passing entry means the
    // bug was fixed and the exemption must be deleted. Analysis and the exact
    // reproducer live in the named requirement note.
    // Empty: every ported-ability fixture currently matches the pinned
    // reference. `magicbounce_reflects_status_7216` is a *pending* fixture
    // (Ability::Magicbounce is not ported), so it is smoke-checked instead of
    // boundary-compared until the reflected-hit draw accounting lands.
    // Empty: every ported-ability fixture currently matches the pinned
    // reference at every decision boundary. `magicbounce_reflects_status_7216`
    // is a pending fixture (Ability::Magicbounce is not ported), so it is
    // smoke-checked rather than boundary-compared.
    const KNOWN_MISMATCHES: &[(&str, &str)] = &[];
    let dex = Dex::load(Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/data"))).unwrap();
    let corpus: Corpus = serde_json::from_str(include_str!("../data/ability-interactions.json")).unwrap();
    assert_eq!(corpus.oracle_commit, pa3_engine::ORACLE_COMMIT);
    assert_eq!(corpus.format, pa3_engine::FORMAT);
    let generator = sha2::Sha256::digest(include_str!("generate_ability_interactions.mjs").as_bytes());
    assert_eq!(
        format!("{generator:x}"),
        corpus.generator_sha256,
        "ability-interactions.json is stale; run: node engine/tests/generate_ability_interactions.mjs"
    );
    assert!(!corpus.fixtures.is_empty(), "ability interaction corpus is empty");
    let mut ported = 0;
    let mut pending = 0;
    let mut skipped = 0;
    'fixture: for fixture in &corpus.fixtures {
        let ability = dex.id("abilities", &fixture.ability).unwrap();
        if dex.effects.abilities[ability as usize].is_ported() {
            ported += 1;
            let known = KNOWN_MISMATCHES.iter().find(|(name, _)| *name == fixture.name);
            let mut state =
                BattleState::reset(&dex, [&fixture.teams[0], &fixture.teams[1]], fixture.seed, [0, 1]).unwrap();
            let mut replay = || {
                check(&state, &fixture.initial, &format!("{} initial", fixture.name));
                for (index, step) in fixture.steps.iter().enumerate() {
                    let context = format!("{} decision {index} {:?} {}", fixture.name, step.side, step.command);
                    let result = state
                        .step(&dex, step.side, &step.actions)
                        .unwrap_or_else(|e| panic!("{context}: {e}"));
                    assert_eq!(result.outcome.operational_error, None, "{context}");
                    check(&state, &step.expected, &context);
                }
            };
            if let Some((_, note)) = known {
                let attempt = std::panic::catch_unwind(std::panic::AssertUnwindSafe(&mut replay));
                assert!(
                    attempt.is_err(),
                    "{} now matches the reference; delete its KNOWN_MISMATCHES entry ({note})",
                    fixture.name
                );
            } else {
                replay();
            }
        } else {
            // Pending fixture: swap the featured ability for a neutral ported
            // one and require the remainder of the battle to stay inside the
            // native subset (no boundary comparison until the port lands).
            pending += 1;
            let mut teams = fixture.teams.clone();
            for team in &mut teams {
                for member in &mut team.members {
                    if member.ability == ability {
                        // Neutralise the featured ability with a legal ported
                        // ability of the same species so the remainder of the
                        // battle stays inside the native subset. A species with
                        // no other legal ability (Disguise) cannot be smoke
                        // checked and is covered by the ported path instead.
                        let Some(neutral) = dex.legal_abilities_by_species[member.species as usize]
                            .iter()
                            .copied()
                            .find(|&id| dex.effects.abilities[id as usize].is_ported())
                        else {
                            skipped += 1;
                            continue 'fixture;
                        };
                        member.ability = neutral;
                    }
                }
            }
            let mut state = BattleState::reset(&dex, [&teams[0], &teams[1]], fixture.seed, [0, 1]).unwrap();
            // Bounded smoke walk: passive fixture teams may never KO each
            // other, so termination is not required here.
            for guard in 0..200 {
                if state.observe(SideId::P1).outcome.terminated {
                    break;
                }
                let mut progressed = false;
                for side in [SideId::P1, SideId::P2] {
                    let view = state.observe(side);
                    if view.outcome.terminated || view.request.kind == RequestKind::Wait {
                        continue;
                    }
                    let branches = view.request.branch_slots().len();
                    let mut prefix: Vec<AtomicAction> = Vec::new();
                    while prefix.len() < branches {
                        let candidates = view.request.candidates(&prefix).unwrap();
                        let pick = candidates
                            .iter()
                            .find(|action| action.kind == ActionKind::Move && action.move_slot < 8)
                            .or_else(|| candidates.first());
                        let Some(pick) = pick else { break };
                        prefix.push(*pick);
                    }
                    let context = format!("{} pending smoke step {guard}", fixture.name);
                    let result = state
                        .step(&dex, side, &prefix)
                        .unwrap_or_else(|e| panic!("{context}: {e}"));
                    assert_eq!(result.outcome.operational_error, None, "{context}");
                    progressed = true;
                }
                if !progressed {
                    break;
                }
            }
        }
    }
    println!("ability interactions: {ported} ported, {pending} pending, {skipped} skipped smoke");
}
