//! Differential verification for the contact-triggered ability family
//! (Rough Skin, Stamina, Flame Body, Poison Touch).
//!
//! The corpus is generated by `tests/generate_ability_fixtures.mjs` from the
//! pinned Showdown checkout and records the reference state at every decision
//! boundary, including RNG, HP, status, boosts and request legality.
use pa3_engine::{
    actions::{AtomicAction, RequestKind},
    assets::Dex,
    state::{BattleState, SideId, Team},
};
use serde::Deserialize;
use std::path::Path;

#[derive(Deserialize)]
struct Corpus {
    oracle_commit: String,
    format: String,
    fixtures: Vec<Fixture>,
}

#[derive(Deserialize)]
struct Fixture {
    name: String,
    seed: [u16; 4],
    teams: [Team; 2],
    initial: Expected,
    steps: Vec<Step>,
}

#[derive(Deserialize)]
struct Step {
    side: SideId,
    actions: Vec<AtomicAction>,
    command: String,
    expected: Expected,
}

#[derive(Deserialize)]
struct Expected {
    turn: u16,
    rng: String,
    ended: bool,
    winner: Option<String>,
    sides: Vec<ExpectedSide>,
}

#[derive(Deserialize)]
struct ExpectedSide {
    request: ExpectedRequest,
    pokemon: Vec<ExpectedMon>,
}

#[derive(Deserialize)]
struct ExpectedRequest {
    kind: RequestKind,
    moves: Vec<Vec<(u16, u8, bool)>>,
}

#[derive(Deserialize)]
struct ExpectedMon {
    roster: u8,
    #[allow(dead_code)]
    species: u16,
    hp: u16,
    max_hp: u16,
    fainted: bool,
    active_slot: Option<u8>,
    status: u16,
    boosts: [i8; 7],
    stats: [u16; 6],
    ability: u16,
    ability_ending: bool,
    item: u16,
    types: Vec<u16>,
    pp: Vec<u8>,
    disabled: Vec<bool>,
    volatiles: Vec<u16>,
}

fn world(state: &BattleState) -> serde_json::Value {
    let envelope: serde_json::Value = serde_json::from_slice(&state.snapshot().unwrap()).unwrap();
    serde_json::from_str(envelope["payload"].as_str().unwrap()).unwrap()
}

fn check(_dex: &Dex, state: &BattleState, expected: &Expected, context: &str) {
    let world = world(state);
    assert_eq!(world["turn"].as_u64().unwrap() as u16, expected.turn, "{context} turn");
    assert_eq!(
        state
            .rng_seed()
            .iter()
            .map(|x| x.to_string())
            .collect::<Vec<_>>()
            .join(","),
        expected.rng,
        "{context} RNG"
    );
    for (index, expected_side) in expected.sides.iter().enumerate() {
        let side = if index == 0 { SideId::P1 } else { SideId::P2 };
        let view = state.observe(side);
        assert_eq!(view.outcome.terminated, expected.ended, "{context} terminated");
        if expected.ended {
            assert_eq!(
                view.outcome.winner.map(|w| if w == SideId::P1 { "p1" } else { "p2" }),
                expected.winner.as_deref(),
                "{context} winner"
            );
        }
        assert_eq!(view.request.kind, expected_side.request.kind, "{context} request kind");
        if expected_side.request.kind == RequestKind::Normal {
            for (slot, moves) in expected_side.request.moves.iter().enumerate() {
                if moves.is_empty() {
                    continue;
                }
                let actual: Vec<(u16, u8, bool)> = view.request.slots[slot]
                    .moves
                    .iter()
                    .map(|m| (m.id, m.pp, m.disabled))
                    .collect();
                assert_eq!(actual, *moves, "{context} request moves slot {slot}");
            }
        }
        for expected_mon in &expected_side.pokemon {
            let mon = &world["sides"][index]["pokemon"][expected_mon.roster as usize];
            let own = &view.own.pokemon[expected_mon.roster as usize];
            let label = format!("{context} side {index} mon {}", expected_mon.roster);
            assert_eq!(mon["hp"].as_u64().unwrap() as u16, expected_mon.hp, "{label} hp");
            assert_eq!(own.stats[0], expected_mon.max_hp, "{label} max hp");
            assert_eq!(mon["fainted"].as_bool().unwrap(), expected_mon.fainted, "{label} fainted");
            assert_eq!(
                mon["active_slot"].as_u64().map(|x| x as u8),
                expected_mon.active_slot,
                "{label} active slot"
            );
            assert_eq!(own.status, expected_mon.status, "{label} status");
            assert_eq!(own.boosts, expected_mon.boosts, "{label} boosts");
            assert_eq!(own.stats, expected_mon.stats, "{label} stats");
            assert_eq!(own.ability, expected_mon.ability, "{label} ability");
            assert_eq!(
                mon["ability_ending"].as_bool().unwrap_or(false),
                expected_mon.ability_ending,
                "{label} ability ending"
            );
            assert_eq!(own.item, expected_mon.item, "{label} item");
            assert_eq!(own.types, expected_mon.types, "{label} types");
            assert_eq!(
                own.moves.iter().map(|m| m.pp).collect::<Vec<_>>(),
                expected_mon.pp,
                "{label} pp"
            );
            assert_eq!(
                own.moves.iter().map(|m| m.disabled).collect::<Vec<_>>(),
                expected_mon.disabled,
                "{label} disabled flags"
            );
            let mut volatiles: Vec<u16> = mon["volatiles"]
                .as_object()
                .unwrap()
                .keys()
                .map(|id| id.parse().unwrap())
                .collect();
            volatiles.sort_unstable();
            assert_eq!(volatiles, expected_mon.volatiles, "{label} volatiles");
        }
    }
}

#[test]
fn contact_abilities_match_reference_at_every_boundary() {
    let dex = Dex::load(Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/data"))).unwrap();
    let corpus: Corpus =
        serde_json::from_str(include_str!("ability-fixtures.json")).unwrap();
    assert_eq!(corpus.oracle_commit, pa3_engine::ORACLE_COMMIT);
    assert_eq!(corpus.format, pa3_engine::FORMAT);
    assert!(!corpus.fixtures.is_empty());
    for fixture in &corpus.fixtures {
        let mut state =
            BattleState::reset(&dex, [&fixture.teams[0], &fixture.teams[1]], fixture.seed, [0, 1])
                .unwrap();
        check(&dex, &state, &fixture.initial, &format!("{} initial", fixture.name));
        for (index, step) in fixture.steps.iter().enumerate() {
            let context = format!("{} decision {index} {:?} {}", fixture.name, step.side, step.command);
            let result = state
                .step(&dex, step.side, &step.actions)
                .unwrap_or_else(|e| panic!("{context}: {e}"));
            assert_eq!(result.outcome.operational_error, None, "{context}");
            check(&dex, &state, &step.expected, &context);
        }
        assert!(
            state.observe(SideId::P1).outcome.terminated,
            "{} did not finish",
            fixture.name
        );
    }
}
